name: Another

on:
  workflow_dispatch:
    inputs:
      m:
        description: "act!"
        default: "value3"
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch deployment
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Test
          token: ${{ secrets.WORKFLOW_DISPATCH3 }}
          inputs: '{ "actor": "${{ github.event.inputs.m }}"}'
