name: Test

on:
  workflow_dispatch:
    inputs:
      actor:
        description: "act!"
        default: $GITHUB_ACTOR
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
