name: Test

on:
  workflow_dispatch:
    inputs:
      actor:
        description: "act!"
          #default: ""
        required: false

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: baba
        run: |
          echo ${{ github.event.inputs.actor }}
          [ -z ${{ github.event.inputs.actor }} ] && namespace=$GITHUB_ACTOR || namespace=${{ github.event.inputs.actor }}
          echo $namespace
        
