name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      actor:
        description: "act!"
        default: "$GITHUB_ACTOR"
        required: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: baba
        run: |
          [ -z ${{ github.event.inputs.actor }} ] && namespace=$GITHUB_ACTOR || namespace=${{ github.event.inputs.actor }}
          echo $namespace
        